### PR TITLE
Added 6502 time codes documentation file, plus code

### PR DESCRIPTION
**Pull request by mmfoerster**
I have created a plain-text documentation file that explains all the time codes that arise in the 6502 and how/when they occur. It also reveals the occurrence of the T1 and T6 clock states that are not explicitly active time codes.

Accompanying the documentation is code that generates the text representation of the time codes presented in the documentation. The code is an extra (unused) function added to both macros.js and expert-allinone.js, called allTCStates().

Hope you like, thanks for your consideration.
Mark M. Foerster

### CODE REVIEW

**Comment by BigEd** [comment]
Interesting... I have two thoughts:
- the text file should perhaps be in the visual6502 wiki, not in this repo. As a wiki page, we can then use the talk page to discuss, and we can all improve it. I think the ideas may be novel, which might need to be explained.
- we should talk about T-states, not about time codes

I have not fully digested your explanation!

As far as the JS code change goes, it looks like you've defined a new function to display this new view, but there's no way to use it? Perhaps it's worth adding a new case in busToString() in macros.js? We already have "tcstate" and "State" - perhaps "TState" would do?

It would probably be worth a tweak to the wiki explaining these values in the 'logmore' space too...

**Comment by mmfoerster** [comment]
Ahhhh, the wiki instead of a doc file. I still have to adjust myself to the modern way of working.
So... I should create a new page in the wiki with the text I already have for the 6502timecodes.txt file and nevermind having it merged to the repo. Do I need to be added to authorized editors of the wiki?

For adjusting the discussion to be in terms of T-States instead of the manifest time codes, I am unsure of what we'll refer to for the two states that have two active output nodes: T0 T+ and T0 T2. The 6502.jpg reference only mentions eight states with a single label in its "TIMING GENERATION LOGIC" block. We see two more in addition to that, giving us ten states. Stuff to be worked out in the wiki, I suppose? (I think I just answered my own question. The above is thinking out loud combined with fishing for a notational suggestion.)

I'll be happy to add a "TState" case to busToString().

I also had an idea to add one more word to the time code string: "F1" for when the 6502 is in phase 1, "F2" for when the 6502 is in phase 2. That would make a fully complete (unique) time state label.

I had already been manually adding "F1" and "F2" to my printed time codes in local text files for summarizing exactly when various things occur when studying the RES process in detail.

I realize what has been my entire motivation for the new time code function: unique and unambiguous labeling of time state.

Okay, I'll go visit the wiki, now.

THANKS!

**Review by BigEd — CHANGES_REQUESTED** [review]
Sent some additional comments by mail!  Please remove the 6502timecodes.txt as it's now in a better place, at
http://visual6502.org/wiki/index.php?title=6502_Timing_States
(Thanks for doing that.)

**Comment by mmfoerster** [comment]
Okey-dokey! 6502timecodes.txt removed. THANKS!

**Review by BigEd — APPROVED** [review]

**Comment by BigEd** [comment]
Just waiting now for TState vs TStateF discussion to conclude, and perhaps for some feedback on the wiki page.

**Comment by BigEd** [comment]
oops - still need to update expert-allinone.js

**Comment by leahcornelius** [comment]
Hi there, i was wondering if anyone had a local copy of the wiki? Its been down (well its SQL database seems to have been) for a few years now and the most recent working [wayback archive ](https://web.archive.org/web/20210405071425/http://visual6502.org/wiki/index.php?title=Main_Page) seems to be lacking some of the newer content. If there is a git repo or similar it would be much easier to self host a local copy as needed rather than try and use wayback. Thanks for everyone's work on this, i have to say its truly awe inspiring!

**Comment by BigEd** [comment]
There’s an idea of reconstructing the wiki, but it would be using the
Wayback Machine version as the source. In the meantime the best starting
point is I think here
https://web.archive.org/web/20210405071236/http://visual6502.org/wiki/index.php?title=Special%3AAllPages

If there are missing pages it would be good to collect a list.

**Pull request merged**
